### ISSUE TITLE
Stream class refacting suggestions

### ISSUE THREAD

**Issue by aligusnet** [burannah/TwitchSpy#8]
https://github.com/burannah/TwitchXX/blob/1e88f332d48d0b7941b4237de0ae5df56c25bff6/TwitchXX/Stream.cpp#L39

https://github.com/burannah/TwitchXX/blob/1e88f332d48d0b7941b4237de0ae5df56c25bff6/TwitchXX/Stream.cpp#L53-L55

Seems to me you need a function here:

`
bool has_non_empty_field(const T &val, cons std::string &field_name)
{
    return val.has_field("community_ids")
               && !val.at("community_ids").is_null()
               && val.at("community_ids").size());
}
`

https://github.com/burannah/TwitchXX/blob/1e88f332d48d0b7941b4237de0ae5df56c25bff6/TwitchXX/Stream.cpp#L55

20, 100? What are these numbers?

**Comment by aligusnet** [comment]
this pattern repeats in some other palces as well:

https://github.com/burannah/TwitchXX/blob/1e88f332d48d0b7941b4237de0ae5df56c25bff6/TwitchXX/StreamMetadata.cpp#L48

**Comment by burannah** [comment]
All of these were fixed with using `web::json::value::has_array_field`, `web::json::value::has_object_field` etc. 
Thanks!
